-- Truncation script

TRUNCATE TABLE [EDW_100_Staging_Area].dbo.STG_PROFILER_CUST_MEMBERSHIP
TRUNCATE TABLE [EDW_100_Staging_Area].dbo.STG_PROFILER_CUSTOMER_OFFER
TRUNCATE TABLE [EDW_100_Staging_Area].dbo.STG_PROFILER_CUSTOMER_PERSONAL
TRUNCATE TABLE [EDW_100_Staging_Area].dbo.STG_PROFILER_ESTIMATED_WORTH
TRUNCATE TABLE [EDW_100_Staging_Area].dbo.STG_PROFILER_OFFER
TRUNCATE TABLE [EDW_100_Staging_Area].dbo.STG_PROFILER_PERSONALISED_COSTING
TRUNCATE TABLE [EDW_100_Staging_Area].dbo.STG_PROFILER_PLAN
--TRUNCATE TABLE [EDW_100_Staging_Area].dbo.STG_USERMANAGED_SEGMENT

TRUNCATE TABLE [EDW_150_History_Area].dbo.HSTG_PROFILER_CUST_MEMBERSHIP
TRUNCATE TABLE [EDW_150_History_Area].dbo.HSTG_PROFILER_CUSTOMER_OFFER
TRUNCATE TABLE [EDW_150_History_Area].dbo.HSTG_PROFILER_CUSTOMER_PERSONAL
TRUNCATE TABLE [EDW_150_History_Area].dbo.HSTG_PROFILER_ESTIMATED_WORTH
TRUNCATE TABLE [EDW_150_History_Area].dbo.HSTG_PROFILER_OFFER
TRUNCATE TABLE [EDW_150_History_Area].dbo.HSTG_PROFILER_PERSONALISED_COSTING
TRUNCATE TABLE [EDW_150_History_Area].dbo.HSTG_PROFILER_PLAN
TRUNCATE TABLE [EDW_150_History_Area].dbo.HSTG_USERMANAGED_SEGMENT

DELETE FROM [EDW_200_Integration_Layer].dbo.HUB_CUSTOMER --WHERE ETL_INSERT_RUN_ID<>-1
DELETE FROM [EDW_200_Integration_Layer].dbo.HUB_INCENTIVE_OFFER --WHERE ETL_INSERT_RUN_ID<>-1
DELETE FROM [EDW_200_Integration_Layer].dbo.HUB_MEMBERSHIP_PLAN --WHERE ETL_INSERT_RUN_ID<>-1
DELETE FROM [EDW_200_Integration_Layer].dbo.HUB_SEGMENT --WHERE ETL_INSERT_RUN_ID<>-1
TRUNCATE TABLE [EDW_200_Integration_Layer].dbo.LNK_CUSTOMER_COSTING
TRUNCATE TABLE [EDW_200_Integration_Layer].dbo.LNK_CUSTOMER_OFFER
TRUNCATE TABLE [EDW_200_Integration_Layer].dbo.LNK_MEMBERSHIP
TRUNCATE TABLE [EDW_200_Integration_Layer].dbo.LSAT_MEMBERSHIP
TRUNCATE TABLE [EDW_200_Integration_Layer].dbo.LSAT_CUSTOMER_OFFER
TRUNCATE TABLE [EDW_200_Integration_Layer].dbo.LSAT_CUSTOMER_COSTING
TRUNCATE TABLE [EDW_200_Integration_Layer].dbo.SAT_CUSTOMER
TRUNCATE TABLE [EDW_200_Integration_Layer].dbo.SAT_INCENTIVE_OFFER
TRUNCATE TABLE [EDW_200_Integration_Layer].dbo.SAT_MEMBERSHIP_PLAN_DETAIL
TRUNCATE TABLE [EDW_200_Integration_Layer].dbo.SAT_MEMBERSHIP_PLAN_VALUATION
TRUNCATE TABLE [EDW_200_Integration_Layer].dbo.SAT_SEGMENT

