--
-- Link Satellite View definition - regular history for LSAT_CUSTOMER_COSTING
-- Generated at 17/07/2019 1:01:43 PM
--


IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[vedw].[LSAT_CUSTOMER_COSTING]') AND type in (N'V'))
DROP VIEW [vedw].[LSAT_CUSTOMER_COSTING]

GO

CREATE VIEW [vedw].[LSAT_CUSTOMER_COSTING] AS  
SELECT
   HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_CODE1)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_SUFFIX1)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),CUSTOMER_ID2)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),SEGMENT_CODE3)),'NA')+'|'
  ) AS CUSTOMER_COSTING_HSH,
   LOAD_DATETIME AS LOAD_DATETIME,
          [COSTING_EFFECTIVE_DATE],
   COALESCE ( LEAD ( [LOAD_DATETIME] ) OVER
   		     (PARTITION BY 
              PLAN_CODE1,
              PLAN_SUFFIX1,
              CUSTOMER_ID2,
              SEGMENT_CODE3,
              COSTING_EFFECTIVE_DATE
   		     ORDER BY [LOAD_DATETIME]),
   CAST( '9999-12-31' AS DATETIME)) AS LOAD_END_DATETIME,
   CASE
      WHEN ( RANK() OVER (PARTITION BY 
            PLAN_CODE1,
            PLAN_SUFFIX1,
            CUSTOMER_ID2,
            SEGMENT_CODE3,
         COSTING_EFFECTIVE_DATE
          ORDER BY [LOAD_DATETIME] desc )) = 1
      THEN 'Y'
      ELSE 'N'
   END AS CURRENT_RECORD_INDICATOR,
   [RECORD_SOURCE],
    CASE
      WHEN [CDC_OPERATION] = 'Delete' THEN 'Y'
      ELSE 'N'
    END AS [DELETED_RECORD_INDICATOR],
   -1 AS ETL_INSERT_RUN_ID,
   -1 AS ETL_UPDATE_RUN_ID,
   [SOURCE_ROW_ID],
   [CDC_OPERATION],
   PERSONAL_MONTHLY_COST,
   CAST(
      ROW_NUMBER() OVER (PARTITION  BY 
         PLAN_CODE1,
         PLAN_SUFFIX1,
         CUSTOMER_ID2,
         SEGMENT_CODE3,
         COSTING_EFFECTIVE_DATE
      ORDER BY 
         PLAN_CODE1,
         PLAN_SUFFIX1,
         CUSTOMER_ID2,
         SEGMENT_CODE3,
         COSTING_EFFECTIVE_DATE,
         [LOAD_DATETIME]) AS INT)
   AS ROW_NUMBER,
   HASHBYTES('MD5',
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),[CDC_OPERATION])),'NA')+'|'+
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_CODE1)),'NA')+'|'+
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_SUFFIX1)),'NA')+'|'+
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),CUSTOMER_ID2)),'NA')+'|'+
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),SEGMENT_CODE3)),'NA')+'|'+
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),COSTING_EFFECTIVE_DATE)),'NA')+'|'+
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),PERSONAL_MONTHLY_COST)),'NA')+'|'
   ) AS HASH_FULL_RECORD
FROM 
(
  SELECT DISTINCT
    [LOAD_DATETIME],
    [RECORD_SOURCE],
    [SOURCE_ROW_ID],
    [CDC_OPERATION],
      [Plan_Code] AS [PLAN_CODE1],
    'XYZ' AS [PLAN_SUFFIX1],
    CAST([Member] AS NVARCHAR(100)) AS [CUSTOMER_ID2],
ISNULL([Segment], '') +  'TEST'  AS [SEGMENT_CODE3]
    ,[Date_effective] AS [COSTING_EFFECTIVE_DATE],
    Monthly_Cost AS PERSONAL_MONTHLY_COST
  FROM dbo.PSA_PROFILER_PERSONALISED_COSTING
  UNION
  SELECT DISTINCT
    '1900-01-01' AS [LOAD_DATETIME],
    'Data Warehouse' AS [RECORD_SOURCE],
     0 AS [SOURCE_ROW_ID],
    'N/A' AS [CDC_OPERATION],
      [Plan_Code] AS [PLAN_CODE1],
    'XYZ' AS [PLAN_SUFFIX1],
    CAST([Member] AS NVARCHAR(100)) AS [CUSTOMER_ID2],
ISNULL([Segment], '') +  'TEST'  AS [SEGMENT_CODE3],
    Date_effective AS [COSTING_EFFECTIVE_DATE],
    NULL AS [PERSONAL_MONTHLY_COST]
  FROM dbo.PSA_PROFILER_PERSONALISED_COSTING
) sub

--
-- Link Satellite View definition - regular history for LSAT_MEMBERSHIP
-- Generated at 17/07/2019 1:01:46 PM
--
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[vedw].[LSAT_MEMBERSHIP]') AND type in (N'V'))
DROP VIEW [vedw].[LSAT_MEMBERSHIP]
go
CREATE VIEW [vedw].[LSAT_MEMBERSHIP] AS  
SELECT
   HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),CUSTOMER_ID1)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_CODE2)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_SUFFIX2)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),SALES_CHANNEL)),'NA')+'|'
  ) AS MEMBERSHIP_HSH,
   LOAD_DATETIME AS LOAD_DATETIME,
   COALESCE ( LEAD ( [LOAD_DATETIME] ) OVER
   		     (PARTITION BY 
              CUSTOMER_ID1,
              PLAN_CODE2,
              PLAN_SUFFIX2,
              SALES_CHANNEL
   		     ORDER BY [LOAD_DATETIME]),
   CAST( '9999-12-31' AS DATETIME)) AS LOAD_END_DATETIME,
   CASE
      WHEN ( RANK() OVER (PARTITION BY 
            CUSTOMER_ID1,
            PLAN_CODE2,
            PLAN_SUFFIX2,
            SALES_CHANNEL
          ORDER BY [LOAD_DATETIME] desc )) = 1
      THEN 'Y'
      ELSE 'N'
   END AS CURRENT_RECORD_INDICATOR,
   [RECORD_SOURCE],
    CASE
      WHEN [CDC_OPERATION] = 'Delete' THEN 'Y'
      ELSE 'N'
    END AS [DELETED_RECORD_INDICATOR],
   -1 AS ETL_INSERT_RUN_ID,
   -1 AS ETL_UPDATE_RUN_ID,
   [SOURCE_ROW_ID],
   [CDC_OPERATION],
   MEMBERSHIP_END_DATE,
   MEMBERSHIP_START_DATE,
   MEMBERSHIP_STATUS,
   CAST(
      ROW_NUMBER() OVER (PARTITION  BY 
         CUSTOMER_ID1,
         PLAN_CODE2,
         PLAN_SUFFIX2,
         SALES_CHANNEL
      ORDER BY 
         CUSTOMER_ID1,
         PLAN_CODE2,
         PLAN_SUFFIX2,
         SALES_CHANNEL,
         [LOAD_DATETIME]) AS INT)
   AS ROW_NUMBER,
   HASHBYTES('MD5',
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),[CDC_OPERATION])),'NA')+'|'+
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),CUSTOMER_ID1)),'NA')+'|'+
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_CODE2)),'NA')+'|'+
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_SUFFIX2)),'NA')+'|'+
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),MEMBERSHIP_END_DATE)),'NA')+'|'+
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),MEMBERSHIP_START_DATE)),'NA')+'|'+
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),MEMBERSHIP_STATUS)),'NA')+'|'
   ) AS HASH_FULL_RECORD
FROM 
(
  SELECT DISTINCT
    [LOAD_DATETIME],
    [RECORD_SOURCE],
    [SOURCE_ROW_ID],
    [CDC_OPERATION],
    CAST([CustomerID] AS NVARCHAR(100)) AS [CUSTOMER_ID1],
      [Plan_Code] AS [PLAN_CODE2],
    'XYZ' AS [PLAN_SUFFIX2]
    ,[Status] AS [SALES_CHANNEL],
    End_Date AS MEMBERSHIP_END_DATE,
    Start_Date AS MEMBERSHIP_START_DATE,
    Status AS MEMBERSHIP_STATUS
  FROM dbo.PSA_PROFILER_CUST_MEMBERSHIP
  WHERE 17=17
  UNION
  SELECT DISTINCT
    '1900-01-01' AS [LOAD_DATETIME],
    'Data Warehouse' AS [RECORD_SOURCE],
     0 AS [SOURCE_ROW_ID],
    'N/A' AS [CDC_OPERATION],
    CAST([CustomerID] AS NVARCHAR(100)) AS [CUSTOMER_ID1],
      [Plan_Code] AS [PLAN_CODE2],
    'XYZ' AS [PLAN_SUFFIX2],
    [Status] AS [SALES_CHANNEL],
    NULL AS [MEMBERSHIP_END_DATE],
    NULL AS [MEMBERSHIP_START_DATE],
    NULL AS [MEMBERSHIP_STATUS]
  FROM dbo.PSA_PROFILER_CUST_MEMBERSHIP
) sub

--
-- Link Satellite View definition - Driving Key for LSAT_CUSTOMER_OFFER
-- Generated at 17/07/2019 1:01:52 PM
--


GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[vedw].[LSAT_CUSTOMER_OFFER]') AND type in (N'V'))
DROP VIEW [vedw].[LSAT_CUSTOMER_OFFER]
go
CREATE VIEW [vedw].[LSAT_CUSTOMER_OFFER] AS  
SELECT
   HASHBYTES('MD5',
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),[CUSTOMER_ID1])),'NA')+'|'+
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),[OFFER_ID2])),'NA')+'|'
   ) AS CUSTOMER_OFFER_HSH,
   --[CUSTOMER_ID1],
   --[OFFER_ID2],
   LOAD_DATETIME AS LOAD_DATETIME,
   COALESCE ( LEAD ( LOAD_DATETIME ) OVER
      (PARTITION BY 
       [CUSTOMER_ID1]
   	  ORDER BY LOAD_DATETIME),
      CAST( '9999-12-31' AS DATETIME)
   ) AS LOAD_END_DATETIME,
   CASE 
     WHEN ( LEAD ( LOAD_DATETIME ) OVER
      (PARTITION BY 
       [CUSTOMER_ID1]
   	  ORDER BY LOAD_DATETIME)
      ) IS NULL
     THEN 'Y' ELSE 'N'
   END AS CURRENT_RECORD_INDICATOR,
   [RECORD_SOURCE],
    CASE
      WHEN [CDC_OPERATION] = 'Delete' THEN 'Y'
      ELSE 'N'
    END AS [DELETED_RECORD_INDICATOR],
   [SOURCE_ROW_ID],
   [CDC_OPERATION],
   CAST(
      ROW_NUMBER() OVER (PARTITION  BY 
          [CUSTOMER_ID1]
         ORDER BY 
          [CUSTOMER_ID1],
          [LOAD_DATETIME]) AS INT)
   AS ROW_NUMBER,
   HASHBYTES('MD5',
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),[CDC_OPERATION])),'NA')+'|'+
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),[CUSTOMER_ID1])),'NA')+'|'+
      ISNULL(RTRIM(CONVERT(NVARCHAR(100),[OFFER_ID2])),'NA')+'|'
   ) AS HASH_FULL_RECORD
FROM 
(
  SELECT 
    [LOAD_DATETIME],
    [RECORD_SOURCE],
    [SOURCE_ROW_ID],
    [CDC_OPERATION],
        [CustomerID] AS [CUSTOMER_ID1],
    [OfferID] AS [OFFER_ID2],
    LAG([OfferID], 1, '0') OVER (PARTITION BY [CustomerID] ORDER BY LOAD_DATETIME) AS PREVIOUS_FOLLOWER_KEY1
  FROM dbo.PSA_PROFILER_CUSTOMER_OFFER
  WHERE 7=7
  AND NOT (SOURCE_ROW_ID>1 AND CDC_OPERATION = 'Delete')
  UNION
  SELECT 
    [LOAD_DATETIME],
    [RECORD_SOURCE],
    [SOURCE_ROW_ID],
    [CDC_OPERATION],
    [CUSTOMER_ID1],
    [OFFER_ID2],
    '0' AS PREVIOUS_FOLLOWER_KEY0
  FROM (
    SELECT
    '1900-01-01' AS [LOAD_DATETIME],
    'Data Warehouse' AS [RECORD_SOURCE],
    0 AS [SOURCE_ROW_ID],
    'N/A' AS [CDC_OPERATION],
        [CustomerID] AS [CUSTOMER_ID1],
    [OfferID] AS [OFFER_ID2],
    DENSE_RANK() OVER (PARTITION  BY 
        [CustomerID]
    ORDER BY [LOAD_DATETIME], [CustomerID] ASC) ROWVERSION
  FROM dbo.PSA_PROFILER_CUSTOMER_OFFER
  ) dummysub
  WHERE ROWVERSION=1
) sub
WHERE OFFER_ID2 != PREVIOUS_FOLLOWER_KEY1
-- ORDER BY
--  CUSTOMER_ID1,
--  [LOAD_DATETIME]

