--
-- Link View definition for LNK_CUSTOMER_COSTING
-- Generated at 17/07/2019 1:00:52 PM
--

USE [150_Persistent_Staging_Area]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[vedw].[LNK_CUSTOMER_COSTING]') AND type in (N'V'))
DROP VIEW [vedw].[LNK_CUSTOMER_COSTING]
GO

CREATE VIEW [vedw].[LNK_CUSTOMER_COSTING] AS  
SELECT link.*
FROM
(
SELECT
  HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_CODE1)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_SUFFIX1)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),CUSTOMER_ID2)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),SEGMENT_CODE3)),'NA')+'|'
  ) AS CUSTOMER_COSTING_HSH,
  -1 AS ETL_INSERT_RUN_ID,
  MIN(LOAD_DATETIME) AS LOAD_DATETIME,
  RECORD_SOURCE,
  HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_CODE1)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_SUFFIX1)),'NA')+'|'
  ) AS MEMBERSHIP_PLAN_HSH,
  HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),CUSTOMER_ID2)),'NA')+'|'                                       
  ) AS CUSTOMER_HSH,
  HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),SEGMENT_CODE3)),'NA')+'|'
  ) AS SEGMENT_HSH,
  ROW_NUMBER() OVER (PARTITION  BY
      [PLAN_CODE1],
      [PLAN_SUFFIX1],
      [CUSTOMER_ID2],
      [SEGMENT_CODE3]
  ORDER BY 
      MIN(LOAD_DATETIME)
  ) AS ROW_NR
FROM
(


  SELECT 
    [Plan_Code] AS [PLAN_CODE1],
    'XYZ' AS [PLAN_SUFFIX1],
    CAST([Member] AS NVARCHAR(100)) AS [CUSTOMER_ID2],
   ISNULL([Segment], '') +  'TEST'  AS [SEGMENT_CODE3],     RECORD_SOURCE,
    MIN(LOAD_DATETIME) AS LOAD_DATETIME
  FROM [150_Persistent_Staging_Area].[dbo].[PSA_PROFILER_PERSONALISED_COSTING]
  WHERE
  [Plan_Code] IS NOT NULL AND
 [Member] IS NOT NULL AND
  ISNULL([Segment], '') +  'TEST'  != '' 
  GROUP BY 
    [Plan_Code],
    [Member],
ISNULL([Segment], '') +  'TEST' ,     RECORD_SOURCE



) LINK_selection
GROUP BY
  [PLAN_CODE1],
  [PLAN_SUFFIX1],
  [CUSTOMER_ID2],
  [SEGMENT_CODE3],
  [RECORD_SOURCE]
) link
WHERE ROW_NR=1

--
-- Link View definition for LNK_CUSTOMER_OFFER
-- Generated at 17/07/2019 1:01:00 PM
--
GO
USE [150_Persistent_Staging_Area]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[vedw].[LNK_CUSTOMER_OFFER]') AND type in (N'V'))
DROP VIEW [vedw].[LNK_CUSTOMER_OFFER]
GO

CREATE VIEW [vedw].[LNK_CUSTOMER_OFFER] AS  
SELECT link.*
FROM
(
SELECT
  HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),CUSTOMER_ID1)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),OFFER_ID2)),'NA')+'|'
  ) AS CUSTOMER_OFFER_HSH,
  -1 AS ETL_INSERT_RUN_ID,
  MIN(LOAD_DATETIME) AS LOAD_DATETIME,
  RECORD_SOURCE,
  HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),CUSTOMER_ID1)),'NA')+'|'
  ) AS CUSTOMER_HSH,
  HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),OFFER_ID2)),'NA')+'|'
  ) AS INCENTIVE_OFFER_HSH,
  ROW_NUMBER() OVER (PARTITION BY
      [CUSTOMER_ID1],
      [OFFER_ID2]
  ORDER BY 
      MIN(LOAD_DATETIME)
  ) AS ROW_NR
FROM
(



  SELECT 
    CAST([CustomerID] AS NVARCHAR(100)) AS [CUSTOMER_ID1],
    CAST([OfferID] AS NVARCHAR(100)) AS [OFFER_ID2],
    RECORD_SOURCE,
    MIN(LOAD_DATETIME) AS LOAD_DATETIME
  FROM [150_Persistent_Staging_Area].[dbo].[PSA_PROFILER_CUSTOMER_OFFER]
  WHERE
    [CustomerID] IS NOT NULL AND
    [OfferID] IS NOT NULL 
    AND 7=7
  GROUP BY 
    [CustomerID],
    [OfferID],     
    RECORD_SOURCE
    
    
    
) LINK_selection
GROUP BY
  [CUSTOMER_ID1],
  [OFFER_ID2],
  [RECORD_SOURCE]
) link
WHERE ROW_NR=1

--
-- Link View definition for LNK_MEMBERSHIP
-- Generated at 17/07/2019 1:01:00 PM
--
GO
USE [150_Persistent_Staging_Area]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[vedw].[LNK_MEMBERSHIP]') AND type in (N'V'))
DROP VIEW [vedw].[LNK_MEMBERSHIP]
GO

CREATE VIEW [vedw].[LNK_MEMBERSHIP] AS  
SELECT link.*
FROM
(
SELECT
  HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),CUSTOMER_ID1)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_CODE2)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_SUFFIX2)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),SALES_CHANNEL)),'NA')+'|'
  ) AS MEMBERSHIP_HSH,
  -1 AS ETL_INSERT_RUN_ID,
  MIN(LOAD_DATETIME) AS LOAD_DATETIME,
  RECORD_SOURCE,
  HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),CUSTOMER_ID1)),'NA')+'|'
  ) AS CUSTOMER_HSH,
  HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_CODE2)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_SUFFIX2)),'NA')+'|'
  ) AS MEMBERSHIP_PLAN_HSH,
  SALES_CHANNEL,
  ROW_NUMBER() OVER (PARTITION  BY
      [CUSTOMER_ID1],
      [PLAN_CODE2],
      [PLAN_SUFFIX2],
      [SALES_CHANNEL]
  ORDER BY 
      MIN(LOAD_DATETIME)
  ) AS ROW_NR
FROM
(
  SELECT 
       CAST([CustomerID] AS NVARCHAR(100)) AS [CUSTOMER_ID1],
      [Plan_Code] AS [PLAN_CODE2],
    'XYZ' AS [PLAN_SUFFIX2],     RECORD_SOURCE,
    [Status] AS [SALES_CHANNEL],
    MIN(LOAD_DATETIME) AS LOAD_DATETIME
  FROM [150_Persistent_Staging_Area].[dbo].[PSA_PROFILER_CUST_MEMBERSHIP]
  WHERE
  [CustomerID] IS NOT NULL AND
 [Plan_Code] IS NOT NULL 
    AND 16=16
  GROUP BY 
    [CustomerID],
    [Plan_Code],     [Status],
    RECORD_SOURCE
) LINK_selection
GROUP BY
  [CUSTOMER_ID1],
  [PLAN_CODE2],
  [PLAN_SUFFIX2],
  [SALES_CHANNEL],
  [RECORD_SOURCE]
) link
WHERE ROW_NR=1

--
-- Link View definition for LNK_RENEWAL_MEMBERSHIP
-- Generated at 17/07/2019 1:01:01 PM
--
GO
USE [150_Persistent_Staging_Area]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[vedw].[LNK_RENEWAL_MEMBERSHIP]') AND type in (N'V'))
DROP VIEW [vedw].[LNK_RENEWAL_MEMBERSHIP]
GO

CREATE VIEW [vedw].[LNK_RENEWAL_MEMBERSHIP] AS  
SELECT link.*
FROM
(
SELECT
  HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_CODE1)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_SUFFIX1)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_CODE2)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_SUFFIX2)),'NA')+'|'
  ) AS RENEWAL_MEMBERSHIP_HSH,
  -1 AS ETL_INSERT_RUN_ID,
  MIN(LOAD_DATETIME) AS LOAD_DATETIME,
  RECORD_SOURCE,
  HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_CODE1)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_SUFFIX1)),'NA')+'|'
  ) AS MEMBERSHIP_PLAN_HSH,
  HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_CODE2)),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),PLAN_SUFFIX2)),'NA')+'|'
  ) AS RENEWAL_PLAN_HSH,
  ROW_NUMBER() OVER (PARTITION  BY
      [PLAN_CODE1],
      [PLAN_SUFFIX1],
      [PLAN_CODE2],
      [PLAN_SUFFIX2]
  ORDER BY 
      MIN(LOAD_DATETIME)
  ) AS ROW_NR
FROM
(
  SELECT 
         [Plan_Code] AS [PLAN_CODE1],
    'XYZ' AS [PLAN_SUFFIX1],
      [Renewal_Plan_Code] AS [PLAN_CODE2],
    'XYZ' AS [PLAN_SUFFIX2],     RECORD_SOURCE,
    MIN(LOAD_DATETIME) AS LOAD_DATETIME
  FROM [150_Persistent_Staging_Area].[dbo].[PSA_PROFILER_PLAN]
  WHERE
  [Plan_Code] IS NOT NULL AND
 [Renewal_Plan_Code] IS NOT NULL 
    AND 1=1
  GROUP BY 
    [Plan_Code],
    [Renewal_Plan_Code],     RECORD_SOURCE
) LINK_selection
GROUP BY
  [PLAN_CODE1],
  [PLAN_SUFFIX1],
  [PLAN_CODE2],
  [PLAN_SUFFIX2],
  [RECORD_SOURCE]
) link
WHERE ROW_NR=1

