--
-- Hub View definition for HUB_CUSTOMER
-- Generated at 10/07/2019 1:18:43 PM
--

USE [150_Persistent_Staging_Area]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[vedw].[HUB_CUSTOMER]') AND type in (N'V'))
DROP VIEW [vedw].[HUB_CUSTOMER]
GO
CREATE VIEW [vedw].[HUB_CUSTOMER] AS  
SELECT hub.*
FROM(  
SELECT
  HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),[CUSTOMER_ID])),'NA')+'|'
  ) AS CUSTOMER_HSH,
  -1 AS ETL_INSERT_RUN_ID,
  MIN(LOAD_DATETIME) AS LOAD_DATETIME,
  RECORD_SOURCE,
    CONVERT(NVARCHAR(100),[CUSTOMER_ID]) AS CUSTOMER_ID,
  ROW_NUMBER() OVER (PARTITION  BY
      [CUSTOMER_ID]
  ORDER BY 
      MIN(LOAD_DATETIME)
  ) AS ROW_NR
FROM
(
  SELECT 
        CAST([CustomerID] AS NVARCHAR(100)) AS [CUSTOMER_ID],
       RECORD_SOURCE,
       MIN(LOAD_DATETIME) AS LOAD_DATETIME
  FROM dbo.PSA_PROFILER_CUSTOMER_PERSONAL
  WHERE
     [CustomerID] IS NOT NULL 
    AND 1=1
  GROUP BY 
        [CustomerID],
    RECORD_SOURCE
UNION
  SELECT 
        CAST([Member] AS NVARCHAR(100)) AS [CUSTOMER_ID],
       RECORD_SOURCE,
       MIN(LOAD_DATETIME) AS LOAD_DATETIME
  FROM dbo.PSA_PROFILER_PERSONALISED_COSTING
  WHERE
     [Member] IS NOT NULL 
  GROUP BY 
        [Member],
    RECORD_SOURCE
UNION
  SELECT 
        CAST([CustomerID] AS NVARCHAR(100)) AS [CUSTOMER_ID],
       RECORD_SOURCE,
       MIN(LOAD_DATETIME) AS LOAD_DATETIME
  FROM dbo.PSA_PROFILER_CUST_MEMBERSHIP
  WHERE
     [CustomerID] IS NOT NULL 
    AND 15=15
  GROUP BY 
        [CustomerID],
    RECORD_SOURCE
UNION
  SELECT 
        CAST([CustomerID] AS NVARCHAR(100)) AS [CUSTOMER_ID],
       RECORD_SOURCE,
       MIN(LOAD_DATETIME) AS LOAD_DATETIME
  FROM dbo.PSA_PROFILER_CUSTOMER_OFFER
  WHERE
     [CustomerID] IS NOT NULL 
    AND 5=5
  GROUP BY 
        [CustomerID],
    RECORD_SOURCE
) HUB_selection
GROUP BY
  [CUSTOMER_ID],
  RECORD_SOURCE
) hub
WHERE ROW_NR = 1
UNION
SELECT 0x00000000000000000000000000000000,
- 1,
'1900-01-01',
'Data Warehouse',
'Unknown',
1 AS ROW_NR

GO

--
-- Hub View definition for HUB_INCENTIVE_OFFER
-- Generated at 10/07/2019 1:18:49 PM
--

USE [150_Persistent_Staging_Area]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[vedw].[HUB_INCENTIVE_OFFER]') AND type in (N'V'))
DROP VIEW [vedw].[HUB_INCENTIVE_OFFER]
GO
CREATE VIEW [vedw].[HUB_INCENTIVE_OFFER] AS  
SELECT hub.*
FROM(
SELECT
  HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),[OFFER_ID])),'NA')+'|'
  ) AS INCENTIVE_OFFER_HSH,
  -1 AS ETL_INSERT_RUN_ID,
  MIN(LOAD_DATETIME) AS LOAD_DATETIME,
  RECORD_SOURCE,
    CONVERT(NVARCHAR(100),[OFFER_ID]) AS OFFER_ID,
  ROW_NUMBER() OVER (PARTITION  BY
      [OFFER_ID]
  ORDER BY 
      MIN(LOAD_DATETIME)
  ) AS ROW_NR
FROM
(
  SELECT 
        CAST([OfferID] AS NVARCHAR(100)) AS [OFFER_ID],
       RECORD_SOURCE,
       MIN(LOAD_DATETIME) AS LOAD_DATETIME
  FROM dbo.PSA_PROFILER_OFFER
  WHERE
     [OfferID] IS NOT NULL 
    AND 3=3
  GROUP BY 
        [OfferID],
    RECORD_SOURCE
UNION
  SELECT 
        CAST([OfferID] AS NVARCHAR(100)) AS [OFFER_ID],
       RECORD_SOURCE,
       MIN(LOAD_DATETIME) AS LOAD_DATETIME
  FROM dbo.PSA_PROFILER_CUSTOMER_OFFER
  WHERE
     [OfferID] IS NOT NULL 
    AND 6=6
  GROUP BY 
        [OfferID],
    RECORD_SOURCE
) HUB_selection
GROUP BY
  [OFFER_ID],
  RECORD_SOURCE
) hub
WHERE ROW_NR = 1
UNION
SELECT 0x00000000000000000000000000000000,
- 1,
'1900-01-01',
'Data Warehouse',
'Unknown',
1 AS ROW_NR

GO

--
-- Hub View definition for HUB_MEMBERSHIP_PLAN
-- Generated at 10/07/2019 1:18:51 PM
--

USE [150_Persistent_Staging_Area]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[vedw].[HUB_MEMBERSHIP_PLAN]') AND type in (N'V'))
DROP VIEW [vedw].[HUB_MEMBERSHIP_PLAN]
GO
CREATE VIEW [vedw].[HUB_MEMBERSHIP_PLAN] AS  
SELECT hub.*
FROM(
SELECT
  HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),[PLAN_CODE])),'NA')+'|'+
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),[PLAN_SUFFIX])),'NA')+'|'
  ) AS MEMBERSHIP_PLAN_HSH,
  -1 AS ETL_INSERT_RUN_ID,
  MIN(LOAD_DATETIME) AS LOAD_DATETIME,
  RECORD_SOURCE,
    CONVERT(NVARCHAR(100),[PLAN_CODE]) AS PLAN_CODE,
    CONVERT(NVARCHAR(100),[PLAN_SUFFIX]) AS PLAN_SUFFIX,
  ROW_NUMBER() OVER (PARTITION  BY
      [PLAN_CODE],
      [PLAN_SUFFIX]
  ORDER BY 
      MIN(LOAD_DATETIME)
  ) AS ROW_NR
FROM
(
  SELECT 
          [Plan_Code] AS [PLAN_CODE],
    'XYZ' AS [PLAN_SUFFIX],
       RECORD_SOURCE,
       MIN(LOAD_DATETIME) AS LOAD_DATETIME
  FROM dbo.PSA_PROFILER_PLAN
  WHERE
     [Plan_Code] IS NOT NULL 
    AND 10=10
  GROUP BY 
        [Plan_Code],
    RECORD_SOURCE
UNION
  SELECT 
          [Renewal_Plan_Code] AS [PLAN_CODE],
    'XYZ' AS [PLAN_SUFFIX],
       RECORD_SOURCE,
       MIN(LOAD_DATETIME) AS LOAD_DATETIME
  FROM dbo.PSA_PROFILER_PLAN
  WHERE
     [Renewal_Plan_Code] IS NOT NULL 
    AND 1=1
  GROUP BY 
        [Renewal_Plan_Code],
    RECORD_SOURCE
UNION
  SELECT 
          [Plan_Code] AS [PLAN_CODE],
    'XYZ' AS [PLAN_SUFFIX],
       RECORD_SOURCE,
       MIN(LOAD_DATETIME) AS LOAD_DATETIME
  FROM dbo.PSA_PROFILER_PERSONALISED_COSTING
  WHERE
     [Plan_Code] IS NOT NULL 
    AND 18=18
  GROUP BY 
        [Plan_Code],
    RECORD_SOURCE
UNION
  SELECT 
          [Plan_Code] AS [PLAN_CODE],
    'XYZ' AS [PLAN_SUFFIX],
       RECORD_SOURCE,
       MIN(LOAD_DATETIME) AS LOAD_DATETIME
  FROM dbo.PSA_PROFILER_ESTIMATED_WORTH
  WHERE
     [Plan_Code] IS NOT NULL 
    AND 12=12
  GROUP BY 
        [Plan_Code],
    RECORD_SOURCE
UNION
  SELECT 
          [Plan_Code] AS [PLAN_CODE],
    'XYZ' AS [PLAN_SUFFIX],
       RECORD_SOURCE,
       MIN(LOAD_DATETIME) AS LOAD_DATETIME
  FROM dbo.PSA_PROFILER_CUST_MEMBERSHIP
  WHERE
     [Plan_Code] IS NOT NULL 
    AND 14=14
  GROUP BY 
        [Plan_Code],
    RECORD_SOURCE
) HUB_selection
GROUP BY
  [PLAN_CODE],
  [PLAN_SUFFIX],
  RECORD_SOURCE
) hub
WHERE ROW_NR = 1
UNION
SELECT 0x00000000000000000000000000000000,
- 1,
'1900-01-01',
'Data Warehouse',
'Unknown',
'Unknown',
1 AS ROW_NR

GO

--
-- Hub View definition for HUB_SEGMENT
-- Generated at 10/07/2019 1:19:02 PM
--

USE [150_Persistent_Staging_Area]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[vedw].[HUB_SEGMENT]') AND type in (N'V'))
DROP VIEW [vedw].[HUB_SEGMENT]
GO
CREATE VIEW [vedw].[HUB_SEGMENT] AS  
SELECT hub.*
FROM(
SELECT
  HASHBYTES('MD5',
    ISNULL(RTRIM(CONVERT(NVARCHAR(100),[SEGMENT_CODE])),'NA')+'|'
  ) AS SEGMENT_HSH,
  -1 AS ETL_INSERT_RUN_ID,
  MIN(LOAD_DATETIME) AS LOAD_DATETIME,
  RECORD_SOURCE,
    CONVERT(NVARCHAR(100),[SEGMENT_CODE]) AS SEGMENT_CODE,
  ROW_NUMBER() OVER (PARTITION  BY
      [SEGMENT_CODE]
  ORDER BY 
      MIN(LOAD_DATETIME)
  ) AS ROW_NR
FROM
(
  SELECT 
    ISNULL([Segment], '') +  'TEST'  AS [SEGMENT_CODE],
       RECORD_SOURCE,
       MIN(LOAD_DATETIME) AS LOAD_DATETIME
  FROM dbo.PSA_PROFILER_PERSONALISED_COSTING
  WHERE
    ISNULL([Segment], '') +  'TEST'  != '' 
  GROUP BY 
    ISNULL([Segment], '') +  'TEST' ,
    RECORD_SOURCE
UNION
  SELECT 
    ISNULL([Demographic_Segment_Code], '') +  'TEST'  AS [SEGMENT_CODE],
       RECORD_SOURCE,
       MIN(LOAD_DATETIME) AS LOAD_DATETIME
  FROM dbo.PSA_USERMANAGED_SEGMENT
  WHERE
    ISNULL([Demographic_Segment_Code], '') +  'TEST'  != '' 
    AND 8=8
  GROUP BY 
    ISNULL([Demographic_Segment_Code], '') +  'TEST' ,
    RECORD_SOURCE
) HUB_selection
GROUP BY
  [SEGMENT_CODE],
  RECORD_SOURCE
) hub
WHERE ROW_NR = 1
UNION
SELECT 0x00000000000000000000000000000000,
- 1,
'1900-01-01',
'Data Warehouse',
'Unknown',
1 AS ROW_NR

GO

